#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//bool a = false;
task main()
{
	int a = 127;
	playImmediateTone(400, 10);
	servo[servo1] = 0;
	sleep(5000);
	playImmediateTone(400, 10);
	servo[servo1] = a;
	sleep(5000);
	playImmediateTone(400, 10);
	servo[servo1] = 256;
	sleep(5000);
	playImmediateTone(400, 10);
	servo[servo1] = a;
	sleep(5000);
	/*
	while(true)
	{
	a = !a;
	if(a) servo[servo1] = 255;
	else servo[servo1] = 0;
	sleep(3000);
	}*/
}
