#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// :: Definitions ::
#define DEBUG
//#define AUTO
#define TELE

// :: Includes ::
#include "definitions.h"
#include "math.c"

#ifdef TELE
#include "teleop.c"
#endif
#ifdef AUTO
//#include "auto.c"
#endif

// :: Global Type Definitions ::
enum Mode
{
	Autonomous,
	Teleop,
	Finished
};

#pragma debuggerWindows("joystickGame");

// : Local Variables :
float TotalTime = 0.0;
#ifdef AUTO
Mode RobotMode = Autonomous;
#else
Mode RobotMode = Teleop;
#endif
bool Running = true;
int VolumeStore;

/*
* Initialize the Robot and ensure that the software is ready to operate.
*/
void Init()
{
	VolumeStore = nVolume; // Store the Initial Volume Setting
	nVolume = 4; // Maximum Volume
	if(RobotMode == Autonomous)
	{
#ifdef DEBUG
		clearTimer(T1);
#endif


		// Run Startup Code
		waitForStart();

#ifdef DEBUG
		long init_time = time1(T1);
		string sa = "M9 Software Initialised: ";
		string sb;
		stringFormat(sb, "%1.0f", init_time); // init_time to string > sb
		string sc = "ms";
		strcat(sa,sb); // Combine string sa & sb
		strcat(sa,sc); // Combine string sa & sc
		writeDebugStreamLine(sa); // Debug the initialize time
#endif
	}
	else if(RobotMode == Teleop)
	{
		Init_Teleop();
	}
}

/*
* Ends the current Robot Mode and ensures that the software is ready to operate
* in a new state.
*/
void EndState()
{
#ifdef AUTO
	if (RobotMode == Autonomous)
	{
		Autonomous_End(); // Update Autonomous Mode
		RobotMode = Teleop;
#ifdef DEBUG
		writeDebugStreamLine("Autonomous Mode End!"); // Debug
#endif
		Init();
	}
#endif
#ifdef TELE
	if (RobotMode == Teleop)
	{
		End_Teleop(); // Update Drive Mode
#ifdef DEBUG
		writeDebugStreamLine("Teleop Mode End!"); // Debug
#endif
		Running = false;
		RobotMode = Finished;
	}
#endif
	if (RobotMode == Autonomous)
	{
		nVolume = VolumeStore; // Restore the Initial Volume Setting
	}
}

/*
* Call the main update functions of all the inuse functionality
* Update the current mode that the robot is using. Autonomous/Drive
*/
void Update()
{
	alive(); // Reset sleep timer
	// Calculate Elapsed Time
	float delta = GetTime(T1);
	TotalTime += delta; // Accumulate time
	time1[T1] = 0;

#ifdef AUTO
	if (RobotMode == Autonomous)
	{
		if (totaltime >= 30.0)  // End autonomous after 30 seconds
		{
			PlayImmediateTone(300, 20);
			EndState();
		}
	}
#endif
#ifdef TELE
#ifdef AUTO
	else
#endif
	if (RobotMode == Teleop)
	{
		Update_Teleop(); // Update Drive Mode
#ifdef DEBUG
		if(ControllerA.Buttons.Start == ButtonState_Pressed) EndState();
#endif
	}
#endif
	if (ControllerA.Buttons.LeftStick == ButtonState_Active) playImmediateTone(500, 1); // Input Test aka Horn
}

/*
* Application Entry Point
*/
task main
{
	// Defaults servos
	servo[Servo_Arm_Left] = 30;
	servo[Servo_Arm_Right] = 30;
	servo[Servo_GoalKeeper] = 100;
	// Set motor exhaust to 1/4 speed (TEMP)
	motor[Motor_Exhaust] = -25;
	Init();
	while (Running)
	{
		// Update
		Update();
		sleep(2);
	}
	EndState();
}
