#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorMatrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define VISUALSTUDIO // Allows for editing inside of the visual studio editor with correcy syntax highlighting
#ifdef VISUALSTUDIO
// Visual Studio IDE Formatting
double motor[];
double servo[];
int motorA, motorB, motorC, motorD, motorE, motorF, motorG, S1, S2, S3, S4, servoA, servoB, servoC, servoD, servoE, servoF, servoG, servo1, servo2, servo3, servo4;
struct Joystick
{
	signed char joy1_x1, joy1_y1, joy1_x2, joy1_y2, joy1_TopHat;
} joystick;
void getJoystickSettings(Joystick) {};
float sqrt(float);
int joy1Btn(int);
void PlayImmediateTone(int, int);
float pi = 3.1416;
void Sleep(double);
void Sleep(int);
void Sleep(float);
void nxtDisplayClearTextLine(int);
typedef struct { void; } string;
void StringFormat(string, char*, int);
void nxtDisplayTextLine(int, string);
int SensorValue[];
typedef int bool;
typedef int byte;
typedef unsigned int unsigned byte;
#define true 1
#define false 0
#define task void
#endif

// :: SENSORS ::
#define IRSensor S4
#define LightSensor S3

// :: MOTORS ::
#include "motors.c"

// :: SERVOS ::
#define ServoIR srvo_Matrix_S2_1
#define ServoIRArm srvo_Matrix_S2_3

// :: Global Type Definitions ::
typedef enum
{
	Autonomous,
	Drive
} Mode;

#pragma debuggerWindows("joystickGame");
float totaltime = 0.0;

#include "AsyncDrive.c"
//#include "AsyncAutonomous.c"
#include "Definitions.h"

// :: Type Defintions ::

// :: Variables ::
Mode RobotMode = Drive;
const float timescale = 40.0 / 30.0;
const float delta = timescale * 10.0 / 1000.0;


/*
* Call the main update functions of all the inuse functionality
* Update the current mode that the robot is using. Autonomous/Drive
*/
void Update(float delta)
{
	totaltime += delta;
	//if (totaltime >= 0.0 && RobotMode == Autonomous) { PlayImmediateTone(300, 20); Autonomous_End(); RobotMode = Drive; }; // End autonomous after 30 seconds
	if (RobotMode == Drive) Drive_Update(delta); // Update Drive Mode
	}

void End()
{
	//if (RobotMode == Autonomous) Autonomous_End(); // Update Autonomous Mode
	if (RobotMode == Drive) Drive_End(); // Update Drive Mode
}

task main
{
	//waitForStart_II();
	while (true)
	{
		//servo[ServoIRArm] = 30;
		//Light_Update(delta, S3); // Update the wheel light sensor
		Update(delta);
		DrawDebug();

		Sleep(10);
	}
}
